# Generated by Django 2.2.19 on 2022-05-31 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220529_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientmount',
            old_name='mount',
            new_name='amount',
        ),
    ]
