# Generated by Django 2.2.19 on 2022-06-06 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20220605_1514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
