#USERS

### Subscriptions list
GET http://127.0.0.1:8000/api/users/subscriptions/
Content-Type: application/json
# for example:
Authorization: token 8921055979d3c777f5ad87ddb05ebab4b646daf9


### subscribe user
POST http://127.0.0.1:8000/api/users/1/subscribe/?recipes_limit=2
Content-Type: application/json
# for example:
#Authorization: token 8921055979d3c777f5ad87ddb05ebab4b646daf9
Authorization: token 403bbe88a0e5a44ab27e1c2336230c5e8c1c85d9

### unsubscribe user
DELETE http://127.0.0.1:8000/api/users/1/subscribe/
Content-Type: application/json
# for example:
#Authorization: token 8921055979d3c777f5ad87ddb05ebab4b646daf9
Authorization: token 403bbe88a0e5a44ab27e1c2336230c5e8c1c85d9