#USERS

### Users list
GET http://127.0.0.1:8000/api/users/
Content-Type: application/json

### Create user
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json
# for example:

{
    "email": "oland3@mail.ru",
    "username": "oland3",
    "first_name": "volan",
    "last_name": "demort",
    "password": "12345"
    }

### Take token for user oland2
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json
# for example:

{
    "email": "oland2@mail.ru",
    "password": "12345"
    }

### Current user
GET http://127.0.0.1:8000/api/users/me/
Content-Type: application/json
# for example:
Authorization: token 8921055979d3c777f5ad87ddb05ebab4b646daf9

### Take token for admin
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json
# for example:

{
    "email": "admin@mail.ru",
    "password": "admin"
    }