#USERS

### Users list
GET http://127.0.0.1:8000/api/users/
Content-Type: application/json

### Create user
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json
# for example:

{
    "email": "oland3@mail.ru",
    "username": "oland3",
    "first_name": "volan",
    "last_name": "demort",
    "password": "12345"
    }

### Take token for user oland2
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json
# for example:

{
    "email": "oland3@mail.ru",
    "password": "12345"
    }

### Current user
GET http://127.0.0.1:8000/api/users/me/
Content-Type: application/json
# for example:
Authorization: token 94cfbfb2fb6fad765aa4e842bf17ec0c5912f7cb

### Take token for admin
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json
# for example:

{
    "email": "admin@mail.ru",
    "password": "admin"
    }

### Change password for user
POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json
# for example petr:
Authorization: token 94cfbfb2fb6fad765aa4e842bf17ec0c5912f7cb

{
"new_password": "1sds5",
"current_password": "12345"
}