#USERS

### Users list
GET http://127.0.0.1:8000/api/users/
Content-Type: application/json

### Create user
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json
# for example:

{
    "email": "oland4@mail.ru",
    "username": "oland4",
    "first_name": "volan",
    "last_name": "demort",
    "password": "12345Mars"
    }

### Take token for user oland2
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json
# for example:

{
    "email": "oland3@mail.ru",
    "password": "12345Mars"
    }

### Current user
GET http://127.0.0.1:8000/api/users/me/
Content-Type: application/json
# for example:
Authorization: token bcc08aff8319b11fffef84da7cad405c8de7c043

### Take token for admin
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json
# for example:

{
    "email": "admin@mail.ru",
    "password": "admin"
    }

### Change password for user
POST http://127.0.0.1:8000/api/users/set_password/
Content-Type: application/json
# for example petr:
Authorization: token 21e989359c71d5211ff16fb5a7368f475c4ba04c

{
"new_password": "Katrohimets10",
"current_password": "Katrohimets05"
}






    
